services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_REQUEST_TIMEOUT=120000
      - ELASTICSEARCH_STARTUP_TIMEOUT=120000
      - logging.root.level=off
      - logging.appenders.console.type=console
      - logging.appenders.console.layout.type=json
      - logging.loggers.root.level=off
      - logging.loggers.kibana.level=off
      - logging.loggers.plugins.level=off
      - logging.loggers.elasticsearch.level=off
      - logging.loggers.audit.level=off
      - logging.loggers.optimize.level=off
      - logging.loggers.server.level=off
      - logging.loggers.status.level=off
      - logging.loggers.usage.level=off
    volumes:
      - kibana-data:/usr/share/kibana/data
    restart: always

  flower:
    image: nvcr.io/nvstaging/blueprint/foundational-flywheel-server:${TAG:-1.0.0.rc2}
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
      target: dev
    ports:
      - "5555:5555"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis://redis:6379/0
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB=flywheel
      - NGC_API_KEY=${NGC_API_KEY}
    command: ["uv", "run", "celery", "-A", "src.tasks.tasks", "flower", "--port=5555"]
    restart: always

volumes:
  kibana-data:
